openapi: 3.0.1
info:
  title: MySEBAPI
  version: 1.5.1
  description: this great api from SEB
  termsOfService: https://www.example.com/tos
  contact:
    email: contact@example.com
    name: IT Team
    url: https://www.example.com/contact
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: http://localhost:3000
    variables: {}
    description: local fake server
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: my fake api server on github
  - url: '{scheme}://www.example.com:{port}/{version}'
    variables:
      scheme:
        default: https
        enum:
          - http
          - htps
        description: protocol scheme
      version:
        default: v2
        enum:
          - v2
          - v1
        description: version of api
      port:
        default: '8080'
        enum:
          - '8080'
          - '8000'
        description: server port
paths:
  /users:
    summary: user level operations
    description: fetch users, create new users
    get:
      summary: fetch users from server
      description: returns users from server
      operationId: fetchUsers
      responses:
        '200':
          $ref: '#/components/responses/UserArrayResponseBody'
        default:
          description: Default error sample response
      tags:
        - users
    post:
      summary: create user
      description: store user on server
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/UserPostBody'
      responses:
        '201':
          $ref: '#/components/responses/UserRespBody'
        default:
          description: Default error sample response
      tags:
        - users
  /users/{userId}:
    summary: specific user operation
    description: fetch, update, delete user
    get:
      summary: fetch user
      description: fetch user by id
      operationId: fetchUser
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          $ref: '#/components/responses/UserRespBody'
        default:
          description: Default error sample response
      tags:
        - users
components:
  parameters:
    UserId:
      name: userId
      in: path
      required: true
      schema:
        type: string
        example: 1234abc  
  responses:
    UserArrayResponseBody:
      description: user array
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserArray'
    UserRespBody:
      description: successful
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FullUser'
  requestBodies:
    UserPostBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostNewUser'
  schemas:
    UserArray:
      type: array
      items:
        $ref: '#/components/schemas/FullUser'
    PostNewUser:
      type: object
      properties:
        username:
          type: string
          example: bear2133
        score:
          type: integer
          example: 66
        active:
          type: boolean
          example: true
    FullUser:
      allOf:
        - $ref: '#/components/schemas/PostNewUser'
        - type: object
          properties:
            id:
              type: string
              example: 1234asdf
