openapi: 3.0.1
info:
  title: Basic API
  version: '1.0'
  description: Learning API at SEB Campus
  termsOfService: https://example.com/tos
  contact:
    email: contact@example.com
    name: Support
    url: https://example.com/contact
  license:
    name: License
    url: https://example.com/license
servers:
  - url: https://my-json-server.typicode.com/bearc0025/api
    variables: {}
    description: API Design and Development 2022-09-06
